<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Document</title>
</head>
<body>
<script>
    /*
        then里面才是微任务
    */
    const promise = new Promise((resolve, reject) => {
        console.log(1); //主线程
        resolve();
        console.log(2);//主线程
    })
    promise.then(() => {
        console.log(3);//微任务
    })
    console.log(4);   //主线程 

    // 1 2 4 3 


    const promise = new Promise((resolve, reject) => {
        resolve('success1');
        reject('error');
        resolve('success2');
    });
    promise.then((res) => {
        console.log('then:', res);
    }).catch((err) => {
        console.log('catch:', err);
    })

    //'then: success1'



    //then不是函数就穿透,直到then是函数为止
    console.log(Promise.resolve(3))
    Promise.resolve(1)
    .then(2)
    .then(_=>6)
    .then(console.log)


    /*
        红灯3秒亮一次，绿灯1秒亮一次，黄灯2秒亮一次；
        如何让三个灯不断交替重复亮灯？
        （用Promise实现）三个亮灯函数已经存在：
    */
    
    function fn(){
        let p = new Promise((resolve, reject) => {
            setTimeout(() => {
                resolve();
            }, 3000);
        })

        p.then(()=>{
            red();
            return new Promise(function(resolve){
                setTimeout(() => {
                    resolve(); 
                },1000);
            });
        }).then(()=>{
            green();
            return new Promise(function(resolve){
                setTimeout(() => {
                    resolve(); 
                },2000);
            });
        }).then(()=>{
            yellow();
        })
    }
     fn();
     setInterval(fn, 6000);

    function red() {
        console.log('red');
    }
    function green() {
        console.log('green');
    }
    function yellow() {
        console.log('yellow');
    }



    /*
        timeout(2000).then(()=>{成功后的结果})
        如果是用promise.all，三个请求都要请求完毕（不能保证谁先执行谁后执行完），才做别的事情
    */
    const timeout = ms => new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve();
        }, ms);
    });

    const ajax1 = () => timeout(2000).then(() => {
        console.log('1');
        return 1;
    });
    const ajax2 = () => timeout(1000).then(() => {
        console.log('2');
        return 2;
    });
    const ajax3 = () => timeout(2000).then(() => {
        console.log('3');
        return 3;
    });
    const mergePromise = ajaxArray => {
        let r = Promise.resolve(); //创建一个成功的promise对象
        // console.log(r);
        let ary = [];
        //每次循环的时候都把执行函数放到r.then里去执行，执行完的返回结果放在ary每一项
        ajaxArray.forEach(item=>{
            r = r.then(item).then((d)=>{
                ary.push(d);
                return ary; //[1,2,3]
            });
        });
        return r;
    };

    mergePromise([ajax1, ajax2, ajax3]).then((data) => {
        console.log('done');
        console.log(data); // data 为 [1, 2, 3]
    });

// 要求分别输出
// 1
// 2
// 3
// done
// [1, 2, 3]




const first = () => (new Promise((resolve, reject) => {
        console.log(3);
        let p = new Promise((resolve, reject) => {
            console.log(7);
            setTimeout(() => {
                console.log(5); 
                resolve(6);
            }, 0)
            resolve(1);
        });
        resolve(2);
        p.then((arg) => {
            console.log(arg);
        });
}));

    first().then((arg) => {
        console.log(arg);
    });
    console.log(4); 

//374125




var urls = ['https://www.kkkk1000.com/images/getImgData/getImgDatadata.jpg', 'https://www.kkkk1000.com/images/getImgData/gray.gif', 'https://www.kkkk1000.com/images/getImgData/Particle.gif', 'https://www.kkkk1000.com/images/getImgData/arithmetic.png', 'https://www.kkkk1000.com/images/getImgData/arithmetic2.gif', 'https://www.kkkk1000.com/images/getImgData/getImgDataError.jpg', 'https://www.kkkk1000.com/images/getImgData/arithmetic.gif', 'https://www.kkkk1000.com/images/wxQrCode2.png'];

console.log(urls)
function loadImg(url) {
    return new Promise((resolve, reject) => {
        const img = new Image()
        img.onload = function () {
            console.log('一张图片加载完成');
            resolve();
        }
        img.onerror = reject;
        img.src = url
    })
};

function fn(n=0,m=3){
    for(let i=n;i<m;i++){
        if(!urls[i])return;
        loadImg(urls[i]).then(()=>{
            console.log(i)
            if(i == 2 || i == 5 ||i == 7){ //2 5 7  
                fn(m,m+3);//3,6    
            }
        });
    }
}
fn(0,3);




    const promise1 = new Promise((resolve, reject) => {
        setTimeout(() => {
            resolve('success')
        }, 1000)
    })
    const promise2 = promise1.then(() => {
        throw new Error('error!!!')
    })
 
    console.log('promise1', promise1);//pending
    console.log('promise2', promise2);//pending
    
    setTimeout(() => {
        console.log('promise1', promise1);//resolved
        console.log('promise2', promise2);//reject
    }, 2000);


    
   

    Promise.resolve(1)
    .then((res) => {
        console.log(res);//1
        return 2
    })
    .catch((err) => {
        return 3
    })
    .then((res) => {
        console.log(res);//2
    })




    const promise = new Promise((resolve, reject) => {
        //宏任务
        setTimeout(() => {
            console.log('once'); //'once'
            resolve('success')
        }, 1000)
    })
    


    const start = Date.now(); //现在的时间戳
    promise.then((res) => {
        console.log(res+'1', Date.now() - start);//success > 1000
    })
    promise.then((res) => {
        //success  ->  2比1要略大一点
        console.log(res+'2', Date.now() - start)
    });


    
    //throw 抛出异常，说明代码错误，会进catch，如果是return new Error('error!!!')不会进catch
    Promise.resolve()
    .then(() => {
        // throw new Error('error!!!')
        return new Error('error!!!')
    })
    .then((res) => {
        console.log('then: ', res)
        // return []
    })
    .catch((err) => {
        console.log('catch: ', err)
    })
    .then((res)=>{
        console.log(res);// 102行的代码没有返回值，所以res是undefined
    });


    //.then 或 .catch 返回的值不能是 promise 本身，否则会造成死循环
    const promise = Promise.resolve()
    .then(() => {
        return promise
    })
    promise.catch(console.error)


    
    Promise.resolve(1)
    .then(2)
    .then(Promise.resolve(3))
    .then(console.log)

    //1


    Promise.resolve()
    .then(function success (res) {
        throw new Error('error')
    }, function fail1 (e) {
        console.error('fail1: ', e)
    })
    .catch(function fail2 (e) {
        console.error('fail2: ', e)
    })

    //fail2:error

</script>
</body>
</html>